# Generated by Django 3.2 on 2022-03-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20220302_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postcode1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
