# Generated by Django 3.2 on 2022-03-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='county',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='city_town',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address2',
        ),
    ]
