# Generated by Django 3.2 on 2022-04-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles1', '0001_initial'),
        ('products', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '2'), (4, '4')], default=1)),
                ('review', models.TextField(blank=True, null=True)),
                ('buy_again', models.BooleanField(default=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles1.userprofile')),
                ('wine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.wine')),
            ],
        ),
        migrations.DeleteModel(
            name='UserReviews',
        ),
    ]
