# Generated by Django 3.2 on 2022-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220427_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5')], default=1),
        ),
    ]
