# Generated by Django 3.2 on 2022-05-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_userreview_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='user_profile',
            new_name='user',
        ),
    ]
