# Generated by Django 3.2 on 2022-05-01 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles1', '0001_initial'),
        ('reviews', '0006_rename_user_profile_userreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles1.userprofile'),
        ),
    ]
