# Generated by Django 3.2 on 2022-05-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_userreview_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='user',
            new_name='user_profile',
        ),
    ]
