# Generated by Django 3.2 on 2022-05-01 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0008_rename_user_userreview_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
