# Generated by Django 3.2 on 2022-05-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220501_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreview',
            old_name='score',
            new_name='rating',
        ),
    ]
