# Generated by Django 3.2 on 2022-05-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('reviews', '0010_rename_score_userreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (4, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='review_name',
            field=models.CharField(default='No Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='wine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.wine'),
        ),
    ]
