# Generated by Django 3.2 on 2022-05-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220506_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='rating',
        ),
    ]
