# Generated by Django 3.2 on 2022-02-10 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('winery', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
