# Generated by Django 3.2 on 2022-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wine_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'verbose_name_plural': 'Wine'},
        ),
        migrations.AddField(
            model_name='wine',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
