# Generated by Django 3.2 on 2022-02-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, default='wines/placeholder.png', null=True, upload_to='wines/'),
        ),
    ]
