# Generated by Django 3.2 on 2022-02-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_wine_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='name',
            new_name='wine_name',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='type',
            new_name='wine_type',
        ),
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
