# Generated by Django 3.2 on 2022-02-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220212_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='rating',
        ),
    ]
