# Generated by Django 3.2 on 2022-02-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_wine_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='wine_type',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Rosé', 'Rosé')], max_length=5),
        ),
    ]
